server {
    listen 8080;
    host 127.0.0.1;
    server_name example.com;

    client_max_body_size 100M;

    location / {
        root /Users/irychkov/Desktop/webserv_team/test_webserv/serverfiles/html;
        index index.html;
        autoindex on;
        methods GET;
    }
	location /put_test/ {
        methods POST;
        upload_store /Users/irychkov/Desktop/webserv_team/test_webserv/serverfiles/uploads;
    }
	location /cgi-bin {
        methods GET POST;
        root /Users/irychkov/Desktop/webserv_team/test_webserv/serverfiles/cgi-bin;
        cgi_extension .bla;
		cgi_interpreter .bla /Users/irychkov/Desktop/webserv_team/test_webserv/serverfiles/cgi-bin/cgi_tester;
    }
	location /post_body {
        upload_store /Users/irychkov/Desktop/webserv_team/test_webserv/serverfiles/uploads;
        methods POST;
    }
	location /directory/ {
        root /Users/irychkov/Desktop/webserv_team/test_webserv/serverfiles/html/YoupiBanane;
        index youpi.bad_extension;
        methods GET;
		cgi_extension .bla;
		cgi_interpreter .bla /Users/irychkov/Desktop/webserv_team/test_webserv/serverfiles/cgi-bin/cgi_tester;
    }
}