server {
    host 127.0.0.1;
    listen 8080;
    server_name iurii.com;

    location / {
        root /home/irychkov/Desktop/webserv/test_webserv/serverfiles/html/iurii/;
        methods GET;
        autoindex on;
        index index.html;
    }
}

server {
    host 127.0.0.1;
    listen 8080;
    server_name kha.com friend.com;

    location / {
        root /home/irychkov/Desktop/webserv/test_webserv/serverfiles/html/kha/;
        methods GET;
        autoindex on;
        index index.html;
    }
}
