server {
    listen 8080;
    host 0.0.0.0;
    server_name "example.com";

    error_page 404 /errors/404.html;
    client_max_body_size 4G;

    location /directory {
        root  ./test_webserv/serverfiles/html/YoupiBanane;
        index index.html;
        autoindex off;
        methods GET POST;
    }

    location /uploads {
        root ./test_webserv/serverfiles/uploads;
        autoindex on;
        methods POST GET;
        upload_store ./test_webserv/serverfiles/uploads;
    }

    location /cgi-bin {
        root ./test_webserv/serverfiles/cgi-bin;
        methods GET POST;
        cgi_extension .py, .sh, .php;
        cgi_interpreter .py /usr/bin/python3;
        cgi_interpreter .sh /usr/bin/bash;
        cgi_interpreter .php /usr/bin/php-cgi;
    }

    location / {
        root  ./test_webserv/serverfiles;
        index index.html;
        autoindex off;
        methods GET POST;
    }
}
