server {
    listen 8001;
    host 127.0.0.1;
    server_name example.com;

    client_max_body_size 100;

    location / {
        root /home/nlouis/webserv/serverfiles/html;
        index index.html;
        autoindex on;
        methods GET;
    }
	location /put_test/ {
        methods POST;
        upload_store /home/nlouis/webserv/serverfiles/uploads;
    }
	location /cgi-bin {
        methods GET POST;
        root /home/nlouis/webserv/serverfiles/cgi-bin;
        cgi_extension .bla;
		cgi_interpreter .bla /home/nlouis/webserv/serverfiles/cgi-bin/ubuntu_cgi_tester;
    }
	location /post_body {
        upload_store /home/nlouis/webserv/serverfiles/uploads;
        methods POST;
    }
	location /directory/ {
        root /home/nlouis/webserv/serverfiles/html/YoupiBanane;
        index youpi.bad_extension;
        methods GET POST;
		cgi_extension .bla;
		cgi_interpreter .bla /home/nlouis/webserv/serverfiles/cgi-bin/ubuntu_cgi_tester;
    }
}
