server {
    listen       8001;
    host         127.0.0.1;
    server_name  example.com;

    client_max_body_size 10m;

    # 1. Static HTML root
    location / {
        root       /home/toonsa/myProjects/webserv/serverfiles/html;
        index      index.html;
        autoindex  on;
        methods    GET;
    }

    # 2. PUT tester endpoint
    location /put_test/ {
        methods      POST;
        upload_store /home/toonsa/myProjects/webserv/serverfiles/uploads;
    }

    # 3. Uploads directory: allow GET + DELETE
    location /uploads/ {
        root       /home/toonsa/myProjects/webserv/serverfiles/uploads;
        autoindex  on;
        methods    GET DELETE;
    }

    # 4. CGI handler
	location /cgi-bin {
		methods         GET POST;
		root            /home/toonsa/myProjects/webserv/serverfiles/cgi-bin;
		cgi_extension   .py;
		cgi_interpreter .py /usr/bin/python3;
	}

    # 5. Simple POST endpoint
    location /post_body {
        methods      POST;
        upload_store /home/toonsa/myProjects/webserv/serverfiles/uploads;
    }

    # 6. Directory listing under YoupiBanane
    location /directory/ {
        root      /home/toonsa/myProjects/webserv/serverfiles/html/YoupiBanane;
        index     youpi.bad_extension;
        autoindex off;
        methods   GET POST;
    }
}