server {
    host 127.0.0.1;
    listen 8080;
    server_name to0nsa-dev.com;

    location / {
        root /home/nlouis/webserv/demo/to0nsa-dev;
        methods GET;
        autoindex on;
        index index.html;
    }
}

server {
    host 127.0.0.1;
    listen 8080;
    server_name kha-dev.com;

    location / {
        root /home/irychkov/Desktop/webserv/serverfiles/html/kha/;
        methods GET;
        autoindex on;
        index index.html;
    }
}

server {
    host 127.0.0.1;
    listen 8080;
    server_name iuri-dev.com;

    location / {
        root /home/irychkov/Desktop/webserv/serverfiles/html/kha/;
        methods GET;
        autoindex on;
        index index.html;
    }
}
